---
title: hakilebara
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
description: 'Hakilebara'

baseurl: ''
url: https://hakilebara.com
twitter_username: hakilebara
github_username: hakilebara
permalink: "/:title"
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
exclude:
  - scripts
